steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/crazyx/rasa', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/crazyx/rasa']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['rollout', 'status', 'deployment', 'rasa']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=bot'
