steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/crazyx/rasa:cao', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/crazyx/rasa:cao']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/crazyx/action:cao', './actions']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/crazyx/action:cao']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'rasa-action-deploy.yaml']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'rasa-deploy.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=bot'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'rasa-action-service.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=bot'
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'rasa-service.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=bot'
