apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rasa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa
  template:
    metadata:
      labels:
        app: rasa
    spec:
      containers:
      - name: rasa
        image: gcr.io/crazyx/rasa:latest
        ports:
        - containerPort: 5005